### ISSUE TITLE
examples/recorders/joinquant_kdata_runner.py运行出错

### ISSUE THREAD

**Issue by Leo-zhanglj** [zvtvz/zvt#179]
Stock1dHfqKdata registered recorders:{'joinquant': <class 'zvt.recorders.joinquant.quotes.jq_stock_kdata_recorder.JqChinaStockKdataRecorder'>}
2021-08-06 22:39:51,236  INFO  MainThread  run to 1/4187
2021-08-06 22:39:51,268  INFO  MainThread  entity_id:stock_sz_000001,evaluate_start_end_size_timestamps result:2021-02-09 00:00:00,None,179,None
2021-08-06 22:39:54,204  ERROR  MainThread  recording data for entity_id:stock_sz_000001,<class 'zvt.domain.quotes.stock.stock_1d_hfq_kdata.Stock1dHfqKdata'>,error:msg:wrong data: b'error: \xe5\xb7\xb2\xe8\xb6\x85\xe8\xbf\x87\xe6\xaf\x8f\xe6\x97\xa5\xe6\x9c\x80\xe5\xa4\xa7\xe6\x9f\xa5\xe8\xaf\xa2\xe6\x95\xb0\xe9\x87\x8f\n\xe6\xb7\xbb\xe5\x8a\xa0\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xe5\xbe\xae\xe4\xbf\xa1\xe5\x85\x8d\xe8\xb4\xb9\xe9\xa2\x86\xe5\x8f\x96\xe6\x9b\xb4\xe5\xa4\x9a\xe9\xa2\x9d\xe5\xba\xa6\xef\xbc\x9b\xe6\x88\x96\xe4\xbb\x98\xe8\xb4\xb9\xe5\x8d\x87\xe7\xba\xa7\xe5\x88\xb02\xe4\xba\xbf\xe6\x9d\xa1/\xe5\xa4\xa9\xef\xbc\x8c\xe8\xaf\xa6\xe6\x83\x85\xe8\xaf\xb7\xe5\x92\xa8\xe8\xaf\xa2\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xef\xbc\x8c\xe5\xbe\xae\xe4\xbf\xa1\xe5\x8f\xb7\xef\xbc\x9aJQData01'
Traceback (most recent call last):
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/jqdatapy/api.py", line 199, in request_jqdata
    df = pd.read_csv(io.BytesIO(resp.content), dtype=dtype, header=header, parse_dates=parse_dates)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 2068, in __init__
    self._validate_parse_dates_presence(self.names)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 1546, in _validate_parse_dates_presence
    f"Missing column provided to 'parse_dates': '{missing_cols}'"
ValueError: Missing column provided to 'parse_dates': 'date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leo/zvt/zvt/contract/recorder.py", line 387, in run
    timestamps=timestamps)
  File "/Users/leo/zvt/zvt/recorders/joinquant/quotes/jq_stock_kdata_recorder.py", line 82, in record
    fq_ref_date=fq_ref_date)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/jqdatapy/api.py", line 131, in get_bars
    fq_ref_date=fq_ref_date, return_type=return_type, parse_dates=parse_dates)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/jqdatapy/api.py", line 201, in request_jqdata
    raise DataError(f'wrong data: {resp.content}')
jqdatapy.api.DataError: msg:wrong data: b'error: \xe5\xb7\xb2\xe8\xb6\x85\xe8\xbf\x87\xe6\xaf\x8f\xe6\x97\xa5\xe6\x9c\x80\xe5\xa4\xa7\xe6\x9f\xa5\xe8\xaf\xa2\xe6\x95\xb0\xe9\x87\x8f\n\xe6\xb7\xbb\xe5\x8a\xa0\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xe5\xbe\xae\xe4\xbf\xa1\xe5\x85\x8d\xe8\xb4\xb9\xe9\xa2\x86\xe5\x8f\x96\xe6\x9b\xb4\xe5\xa4\x9a\xe9\xa2\x9d\xe5\xba\xa6\xef\xbc\x9b\xe6\x88\x96\xe4\xbb\x98\xe8\xb4\xb9\xe5\x8d\x87\xe7\xba\xa7\xe5\x88\xb02\xe4\xba\xbf\xe6\x9d\xa1/\xe5\xa4\xa9\xef\xbc\x8c\xe8\xaf\xa6\xe6\x83\x85\xe8\xaf\xb7\xe5\x92\xa8\xe8\xaf\xa2\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xef\xbc\x8c\xe5\xbe\xae\xe4\xbf\xa1\xe5\x8f\xb7\xef\xbc\x9aJQData01'
2021-08-06 22:39:54,210  ERROR  MainThread  joinquant record kdata:msg:wrong data: b'error: \xe5\xb7\xb2\xe8\xb6\x85\xe8\xbf\x87\xe6\xaf\x8f\xe6\x97\xa5\xe6\x9c\x80\xe5\xa4\xa7\xe6\x9f\xa5\xe8\xaf\xa2\xe6\x95\xb0\xe9\x87\x8f\n\xe6\xb7\xbb\xe5\x8a\xa0\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xe5\xbe\xae\xe4\xbf\xa1\xe5\x85\x8d\xe8\xb4\xb9\xe9\xa2\x86\xe5\x8f\x96\xe6\x9b\xb4\xe5\xa4\x9a\xe9\xa2\x9d\xe5\xba\xa6\xef\xbc\x9b\xe6\x88\x96\xe4\xbb\x98\xe8\xb4\xb9\xe5\x8d\x87\xe7\xba\xa7\xe5\x88\xb02\xe4\xba\xbf\xe6\x9d\xa1/\xe5\xa4\xa9\xef\xbc\x8c\xe8\xaf\xa6\xe6\x83\x85\xe8\xaf\xb7\xe5\x92\xa8\xe8\xaf\xa2\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xef\xbc\x8c\xe5\xbe\xae\xe4\xbf\xa1\xe5\x8f\xb7\xef\xbc\x9aJQData01'
Traceback (most recent call last):
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/jqdatapy/api.py", line 199, in request_jqdata
    df = pd.read_csv(io.BytesIO(resp.content), dtype=dtype, header=header, parse_dates=parse_dates)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 2068, in __init__
    self._validate_parse_dates_presence(self.names)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/pandas/io/parsers.py", line 1546, in _validate_parse_dates_presence
    f"Missing column provided to 'parse_dates': '{missing_cols}'"
ValueError: Missing column provided to 'parse_dates': 'date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leo/zvt/examples/recorders/joinquant_kdata_runner.py", line 42, in record_kdata
    Stock1dHfqKdata.record_data(provider='joinquant', sleeping_time=0, day_data=True)
  File "/Users/leo/zvt/zvt/contract/schema.py", line 175, in record_data
    r.run()
  File "/Users/leo/zvt/zvt/contract/recorder.py", line 468, in run
    raise raising_exception
  File "/Users/leo/zvt/zvt/contract/recorder.py", line 387, in run
    timestamps=timestamps)
  File "/Users/leo/zvt/zvt/recorders/joinquant/quotes/jq_stock_kdata_recorder.py", line 82, in record
    fq_ref_date=fq_ref_date)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/jqdatapy/api.py", line 131, in get_bars
    fq_ref_date=fq_ref_date, return_type=return_type, parse_dates=parse_dates)
  File "/Users/leo/.virtualenvs/zvt/lib/python3.7/site-packages/jqdatapy/api.py", line 201, in request_jqdata
    raise DataError(f'wrong data: {resp.content}')
jqdatapy.api.DataError: msg:wrong data: b'error: \xe5\xb7\xb2\xe8\xb6\x85\xe8\xbf\x87\xe6\xaf\x8f\xe6\x97\xa5\xe6\x9c\x80\xe5\xa4\xa7\xe6\x9f\xa5\xe8\xaf\xa2\xe6\x95\xb0\xe9\x87\x8f\n\xe6\xb7\xbb\xe5\x8a\xa0\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xe5\xbe\xae\xe4\xbf\xa1\xe5\x85\x8d\xe8\xb4\xb9\xe9\xa2\x86\xe5\x8f\x96\xe6\x9b\xb4\xe5\xa4\x9a\xe9\xa2\x9d\xe5\xba\xa6\xef\xbc\x9b\xe6\x88\x96\xe4\xbb\x98\xe8\xb4\xb9\xe5\x8d\x87\xe7\xba\xa7\xe5\x88\xb02\xe4\xba\xbf\xe6\x9d\xa1/\xe5\xa4\xa9\xef\xbc\x8c\xe8\xaf\xa6\xe6\x83\x85\xe8\xaf\xb7\xe5\x92\xa8\xe8\xaf\xa2\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xef\xbc\x8c\xe5\xbe\xae\xe4\xbf\xa1\xe5\x8f\xb7\xef\xbc\x9aJQData01'

**Comment by Leo-zhanglj** [comment]
依赖版本信息
requests == 2.20.1
SQLAlchemy == 1.4.20
pandas == 1.1.4
arrow == 0.11.0
tzlocal == 2.1
xlrd == 1.2.0
demjson == 2.2.4
marshmallow-sqlalchemy == 0.23.1
marshmallow == 3.2.2
plotly==4.12.0
dash==1.17.0
simplejson==3.16.0
jqdatapy==0.1.6
dash-bootstrap-components
dash_daq

**Comment by foolcage** [comment]
jq账号过期？超过限制条数？

**Comment by Leo-zhanglj** [comment]
今天更新了数据，好像是超过了数据条目了。
