### ISSUE TITLE
更新板块数据时会报错

### ISSUE THREAD

**Issue by kingmoon3** [zvtvz/zvt#193]
2022-02-28 21:26:41,721  ERROR  MainThread  report error:'em'
Traceback (most recent call last):
  File "/opt/zvt/examples/recorder_utils.py", line 28, in run_data_recorder
    domain.record_data(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/zvt/contract/schema.py", line 241, in record_data
    recorder_class = cls.provider_map_recorder[provider]
KeyError: 'em'

**Comment by kingmoon3** [comment]
更换不同的provider也是一样的结果

**Comment by foolcage** [comment]
@kingmoon3 examples是跟着源码走的，v0.9.15 Block还没支持 provider em

**Comment by foolcage** [comment]
v0.9.16包含了最近的修改，可直接使用。
examples如果要用pypi发布的版本，可以拉一下tag

git checkout v0.9.16

**Comment by kingmoon3** [comment]
@foolcage 好的
