### ISSUE TITLE
ImportError: cannot import name 'html' from 'dash' 

### ISSUE THREAD

**Issue by bigmarten** [zvtvz/zvt#210]
请问是用什么版本的dash？本机清单中还有什么包的版本不对。
Traceback (most recent call last):
  File "\\?\D:\develop\anaconda3\envs\zvt\Scripts\zvt-script.py", line 33, in <module>
    sys.exit(load_entry_point('zvt==0.10.5', 'console_scripts', 'zvt')())
  File "\\?\D:\develop\anaconda3\envs\zvt\Scripts\zvt-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\develop\anaconda3\envs\zvt\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\develop\anaconda3\envs\zvt\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\develop\anaconda3\envs\zvt\lib\site-packages\zvt-0.10.5-py3.8.egg\zvt\main.py", line 2, in <module>
    from dash import html
ImportError: cannot import name 'html' from 'dash' (D:\develop\anaconda3\envs\zvt\lib\site-packages\dash\__init__.py)

pip包的清单：
Package                   Version
------------------------- ------------
arrow                     1.2.1
blinker                   1.6.2
Brotli                    1.1.0
certifi                   2023.7.22
chardet                   3.0.4
charset-normalizer        3.2.0
click                     8.1.7
colorama                  0.4.6
dash                      1.17.0
dash-bootstrap-components 0.11.0
dash-core-components      1.13.0
dash-daq                  0.5.0
dash-html-components      1.1.1
dash-renderer             1.8.3
dash-table                4.11.0
demjson3                  3.0.5
enum34                    1.1.10
et-xmlfile                1.1.0
Flask                     2.1.3
Flask-Compress            1.13
future                    0.18.3
greenlet                  2.0.2
idna                      2.7
importlib-metadata        6.8.0
itsdangerous              2.1.2
Jinja2                    3.1.2
joblib                    1.3.2
jqdatapy                  0.1.6
MarkupSafe                2.1.3
marshmallow               3.2.2
marshmallow-sqlalchemy    0.23.1
numpy                     1.24.4
openpyxl                  3.1.1
packaging                 23.1
pandas                    1.1.4
pip                       23.2.1
plotly                    4.12.0
python-dateutil           2.8.2
pytz                      2023.3.post1
requests                  2.20.1
retrying                  1.3.4
scikit-learn              1.0.1
scipy                     1.10.1
setuptools                68.0.0
simplejson                3.16.0
six                       1.16.0
SQLAlchemy                1.4.20
tenacity                  8.2.3
threadpoolctl             3.2.0
urllib3                   1.24.3
Werkzeug                  2.0.1
wheel                     0.38.4
xlrd                      1.2.0
zipp                      3.16.2
zvt                       0.10.5

**Comment by xupengrun** [comment]
版本问题 升级到2.x版本解决问题
pip install --upgrade dash
