### ISSUE TITLE
mac M1运行失败

### ISSUE THREAD

**Issue by mafulong** [zvtvz/zvt#221]
pip install zvt后，运行如下命令
python3 -m zvt
{'data_path': '/Users/mafulong/zvt-home/data',
 'log_path': '/Users/mafulong/zvt-home/logs',
 'resource_path': '/Users/mafulong/zvt-home/resources',
 'tmp_path': '/Users/mafulong/zvt-home/tmp',
 'ui_path': '/Users/mafulong/zvt-home/ui',
 'zvt_home': '/Users/mafulong/zvt-home'}
2024-10-28 18:46:32,319  INFO  MainThread  init config for zvt, current_config:{}
{}
2024-10-28 18:46:32,319  INFO  MainThread  current_config:{}
Traceback (most recent call last):
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/zvt/__init__.py", line 233, in <module>
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/zvt/recorders/__init__.py", line 66, in <module>
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/zvt/recorders/__init__.py", line 57, in init_main_index
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/zvt/domain/__init__.py", line 159, in <module>
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/zvt/domain/quotes/__init__.py", line 170, in <module>
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/zvt/domain/quotes/stock/__init__.py", line 121, in <module>
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/zvt/domain/quotes/stock/stock_30m_kdata.py", line 15, in <module>
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/zvt/contract/register.py", line 94, in register_schema
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 5825, in create_all
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3254, in _run_ddl_visitor
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2460, in _run_ddl_visitor
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 918, in visit_metadata
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 956, in visit_table
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 314, in _invoke_with
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1532, in _execute_ddl
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
  File "/Users/mafulong/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
[SQL:
CREATE TABLE stock_30m_kdata (
	provider VARCHAR(32),
	code VARCHAR(32),
	name VARCHAR(32),
	level VARCHAR(32),
	open FLOAT,
	close FLOAT,
	high FLOAT,
	low FLOAT,
	volume FLOAT,
	turnover FLOAT,
	change_pct FLOAT,
	turnover_rate FLOAT,
	id VARCHAR NOT NULL,
	entity_id VARCHAR,
	timestamp DATETIME,
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by foolcage** [comment]
不确定是不是跟sqlite的使用方式有关，可以更新到python3.12并使用最新的依赖看看
