### ISSUE TITLE
[dev][bug] 如果函数放在常驻程序里面运行，会出现异常

### ISSUE THREAD

**Issue by wisfern** [zvtvz/zvt#28]
Traceback (most recent call last):                                                                                                                                  
  File "/home/devis/2.OutlierAnalysis/zvt/zvdata/recorder.py", line 342, in run                                                                                     
    domain_item = self.generate_domain(entity_item, original_item)                                                                                                  
  File "/home/devis/2.OutlierAnalysis/zvt/zvdata/recorder.py", line 242, in generate_domain                                                                         
    entity_id=entity.id, filters=[self.data_schema.id == the_id], return_type='domain')                                                                             
  File "/home/devis/2.OutlierAnalysis/zvt/zvdata/api.py", line 115, in get_data                                                                                     
    return query.all()                                                                                                                                              
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2843, in all                                                
    return list(self)                                                                                                                                               
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__                                           
    return self._execute_and_instances(context)                                                                                                                     
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3016, in _execute_and_instances                             
    close_with_result=True)                                                                                                                                         
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3025, in _get_bind_args                                     
    **kw                                                                                                                                                            
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3007, in _connection_from_session                           
    conn = self.session.connection(**kw)                                                                                                                            
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1046, in connection                                       
    execution_options=execution_options)                                                                                                                            
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1051, in _connection_for_bind                             
    engine, execution_options)                                                                                                                                      
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind                              
    self._assert_active()                                                                                                                                           
  File "/home/devis/2.OutlierAnalysis/zvt/ve/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 264, in _assert_active                                    
    "This session is in 'prepared' state; no further "                                                                                                              
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.  

个人怀疑，跟session的状态有关。我现在的做法是恢复之前的异常捕捉代码。

**Comment by foolcage** [comment]
这个错误应该是　session　在不同的线程里面使用了，常驻进程怎么写的？
如果是自己多线程管理session的话，建议get_db_session时设置force_new=True,每个线程单独管理其生命周期。
